Lotta flag extractor
Learning-from-our-past/kaira-core pull request #38
Opened 2017-10-05 14:11 UTC by jkallioniemi

2017-10-05 21:23 UTC, Tumetsu requested changes
Tähän tuli nyt pari isompaa hommaa, joten ennen seuraavaa mergeä voisin katsoa muutokset sitten uudestaan. Voidaan myös yhdessä miettiä vähän tuota arkkitehtuuria. 

Tämä nyt joka tapauksessa vahvistaa mun tunnetta siitä, että tähän arkkitehtuuriin tarvitaan kyllä joku johdonmukainen riippuvuushallinta, joka pitäis miettiä huolellisesti ennen toteutusta. Mutta se on sitten toinen tarina. Nähdäkseni tämän pystynee vielä ratkaisemaan toistaiseksi sopivasti ilmankin.

2017-10-05 21:23 UTC, Tumetsu commented on book_extractors/karelians/extraction/extractors/tests/test_war_data_extraction.py
> +    def _verify_flags(self, expected_flags_and_texts, extractor):
Hmm, kannattaako tätä kopioida erikseen joka suiteen? Voisiko tehdä hieman geneerisemmän version tästä jolla saisi nuo parametrit yms. konffattua siten, että tässä tiedostossa voisivat kaikki luokat käyttää testeissään samaa funktiota testaamiseen? 

Voisi joko toteuttaa erillisillä parametreilla, tai jos tuntuu hauskalta, niin jonain higher order funktiona, joka palauttaa valmiiksi konffatun funktion jonka scopessa on ne parametrit jotenkin tyyliin:
```
def get_verifier(flag_name, extractor):
    def verify(expected_flags_and_texts):
         # tänne nuo aiemmat kamat, sillä täältä scopesta näkee tuon extractorin
    return verify
```
Sitten generoi jokaiseen suiteen sille sopivan `verifier`:in ja kutsuu sitä sitten testeissä. En nyt ajatellut loppuun asti onko paras ratkaisu, mutta lähinnä ajatuksen ruoaksi jos tällainen patterni (higher order functions) ei ole tuttu konsepti.

2017-10-05 21:23 UTC, Tumetsu commented on book_extractors/karelians/extraction/extractors/tests/test_war_data_extraction.py
> +    def should_return_true_if_text_contains_mention_of_lotta_activity_with_typo(self, extractor):
Tänne pätee toki sama kommentti typoista kuin sinne toiseen testisettiin.

2017-10-05 21:23 UTC, Tumetsu commented on book_extractors/karelians/extraction/extractors/lotta_activity_flag_extractor.py
> +        self.LOTTA_ACTIVITY_PATTERN = r'(?:lotta){s<=1}'
En tiedä onko oleellista kun en ole lähdetekstistä tarkistanut, mutta ajattelitko:
a) Alkaako lottatoiminta aina pienellä l:llä?
b) Tuo substituutio sallii mukaan myös Lotta nimet (l -> L), joten varmaan kaikki Lotta naiset lasketaan mukaan "lottatoimintaan"

Testi casen voisi lisätä tuollaisille tapauksille.

2017-10-05 21:23 UTC, Tumetsu commented on book_extractors/karelians/extraction/extractors/tests/test_war_data_extraction.py
> +    def should_extract_lotta_activity_flag_correctly_as_true_for_spouse_if_male_and_none_for_person(self, extractor):
Mitä tarkoittaa none for person...?

2017-10-05 21:23 UTC, Tumetsu commented on book_extractors/karelians/extraction/extractors/war_data_extractor.py
> +    def _postprocess_extracted_data(self, extracted_data, extraction_results):
Extractoreissa on muuten `_postprocess()` funktio joka ajetaan `_extract()`:n jälkeen. Tosin se on hieman puolivillainen viritys siinä mielessä, että periaatteessa siellä olevat kamat voi tehdä kyllä extractin aikanakin kuten tässä on. Lähinnä lisäsin sen sinne tällaisia selkeitä "kun kamat irrotettu, tee niille vielä jotain transformaatioita" tms. 

En kuitenkaan ihan 100 varma ole sen idean hyvyydestä, ja voipi olla että sille käy hassusti jossain välissä, joten eipä tätä tarvitse sinne siirtää. Lähinnä tiedoksi sellaisestakin. Muistaakseni paikkatietojen kanssa olen sitä käyttänyt, kun irroitettuja paikkatietoja on pitänyt vielä siistiä ja augmentoida jotenkin.

2017-10-05 21:23 UTC, Tumetsu commented on book_extractors/karelians/extraction/extractors/war_data_extractor.py
> +    def _transfer_lotta_flag_to_spouse_if_male(self, extracted_data, extraction_results):
Hmm, mietin olisiko se oikeampi tapa tehdä tämä jotenkin siten, että tämä lotta extractori ajetaan täällä vain jos tämä primary person on mies. Sitten vastaavasti Spouse extractoriin lisäisi tämän lottalipun irroituksen mukaan joka ajettaisiin vain jos kyseessä on nainen? 

Vältyttäisiin sitten tällaisilta kummallisilta extraction_resultsin manipuloinnilta. Ideahan on, että jokaisen aliobjektin kamaa muuttaisi ainoastaan sille määritetty pipeline ja extractorit. Nythän tuonne spouseen sitten vain jotenkin ilmestyy jostain uusi flagi.

Tätä tosin kannattaa sitten hieman miettiä, miten nuo sotajutut spouseen lisätään. Voipi nimittäin olla, että vain osa näistä extractoreista toimii siellä järkevästi, joten saattaa olla ettei sinne kannata tätä `WarDataExtractor`:ia tällaisenaan tunkea, vaan joko suoraan tuo lotta extractor tai kenties ennemmin tekisi tästä extractorista jotenkin konffattavan siten, että se ajaa vain tietyt extractorit (tai excludeaa niitä). Vaatinee hieman miettimistä mutta etköhän jotain keksi ja kysy tarvittaessa niin voidaan funtsia tarkemmin.

2017-10-06 07:37 UTC, jkallioniemi commented on book_extractors/karelians/extraction/extractors/lotta_activity_flag_extractor.py
> +        self.LOTTA_ACTIVITY_PATTERN = r'(?:lotta){s<=1}'
Kyllä, tätä tehdessä katselin noita Lotta nimiä ja niitä oli yllättävän vähän. Lottatoiminta alkaa melkein aina pienellä l:llä paitsi tapauksissa, joissa on mainittu Lotta Svärd, joka on useasti kirjoitettu isolla L:llä. Yritin pitää ehkä regexin turhan siistinä/yksinkertaisen näköisenä. Käyttäkäämme kattavampaa patternia, jonka käyttöä harkitsin aikaisemmin.

2017-11-03 19:39 UTC, closed without merging