Dependency declarations
Learning-from-our-past/kaira-core pull request #41
Opened 2017-10-10 14:07 UTC by jkallioniemi

2017-10-10 20:27 UTC, Tumetsu requested changes
Joo, pari juttua jotka voisi katsoa läpi. En ihan ymmärtänyt tuon dependencies parametrin välitystä initissä, kirjoitin siitä enemmän tuonne kommenttiin. Mut on tää jo ihan hyvään suuntaan, joten noi jutut korjaukseen niin kyllä tästä vielä kalu saadaan.

2017-10-10 20:27 UTC, Tumetsu commented on book_extractors/common/extractors/base_extractor.py
> +            self._dependencies_graph = [(a.extraction_key, b) for a, b in zip(dependencies, dependencies_contexts)]
a ja b voisi nimetä toisinkin :) a = extractor ja b = context

2017-10-10 20:27 UTC, Tumetsu commented on book_extractors/extraction_pipeline.py
> +    :param dependencies_contexts: How to find the exact extractor whose results this extractor depends on
Tässä voisi selittää, että tuo context tarkoittaa missä pipelinessa se extractori sijaitsee, josta ollaan riippuvaisia. Veikkaan että tää ei oo ihan niin selkeetä jos tätä muutaman kuukauden päästä tuijottelee.

2017-10-10 20:27 UTC, Tumetsu commented on book_extractors/common/extractors/tests/test_base_extractor.py
> +class NoPreAndPostProcessesExtractorForDeps(BaseExtractor):
Hmm, mihin tällä pre ja post processeilla viitataan? Siihen että tätä käytetään yksin pipelinessa? Tää on hieman hämäävää kun extractoreissa on erikseen optionaaliset postprocess ja preprocess funkkarit, joten tää kuulostaa vähän siltä että tässä ei niitä ole (ja että se olisi jotenkin merkityksellistä)

Eli tämä voisi olla jotain tyyliin SingleExtractor tjsp.

2017-10-10 20:27 UTC, Tumetsu commented on book_extractors/common/extractors/base_extractor.py
> +    def __init__(self, dependencies_contexts, key_of_cursor_location_dependent=None, options=None, dependencies=None):
Hmm. onko tässä jokin syy välittää nämä `dependencies`:it initissä tänne? Eikös nämä ole niitä extractorissa itsessään julistettuja riippuvuuksia? Eivätkö ne voisi olla vain BaseExtractorin self-muuttujassa, jonne nuo periytetyt extractorit voivat omansa laittaa suoraan? 

Tietysti tällä voi periaatteessa välittää nuo riippuvuudet ulkopuolelta tarvittaessa, oliko se ajatuksena ja jos oli niin oliko sulla mielessä jokin tilanne sille?

2017-10-11 18:50 UTC, Tumetsu approved these changes

2017-10-11 18:50 UTC, Tumetsu commented on book_extractors/common/extractors/base_extractor.py
> +                raise LookupError('There is a mismatch between the amount of dependencies and dependency contexts!'
Tähän erroriin voisi laittaa jos mahdollista niiden puuttuvien kontekstien avaimet tai jotain vastaavaa.

2017-10-12 10:32 UTC, jkallioniemi commented on book_extractors/common/extractors/base_extractor.py
> +            self._build_dependencies_graph(dependencies_contexts)
Tässä käy nyt niin, että jos `dependencies_contexts` on `None` (joka on `dependencies_contexts` default arvo `configure_extractor` funktion ja jokaisen luokan constructorien parametreissa) niin `_dependencies_graph` ei rakennu. Tämä toimii näin sen takia, että annetaan ekaksi superluokkien lisätä omat dependencyt `_set_dependencies` kutsulla `_dependencies` muuttujaan. Näissä kutsuissa `dependencies_contexts` tulee olemaan `None`, koska superluokkien `__init__` kutsutaan aliluokan constructorista, eikä pipelinen luonnin yhteydessä `configure_extractor` kautta. Ainoastaan alin luokka kutsutaan `configure_extractor` kautta.  Kun tuo tapahtuu, sille annetaan sen ja jokaisen yliluokan kontekstit, ja kun se lisää depsinsä `_set_dependencies` kutsulla, `dependencies_contexts` ei olekaan enää `None`, ja graph rakennetaan. Tällä myös vältymme graphin luomiselta n-kertaa.

2017-10-12 10:36 UTC, jkallioniemi commented on book_extractors/common/extractors/base_extractor.py
> +            self._build_dependencies_graph(dependencies_contexts)
Tässä käy nyt niin, että jos `dependencies_contexts` on `None` (joka on `dependencies_contexts` default arvo `configure_extractor` funktion ja jokaisen luokan constructorien parametreissa) niin `_dependencies_graph` ei rakennu. Tämä toimii näin sen takia, että annetaan ekaksi superluokkien lisätä omat dependencyt `_set_dependencies` kutsulla `_dependencies` muuttujaan. Näissä kutsuissa `dependencies_contexts` tulee olemaan `None`, koska superluokkien `__init__` kutsutaan aliluokan constructorista, eikä pipelinen luonnin yhteydessä `configure_extractor` kautta. Ainoastaan alin luokka kutsutaan `configure_extractor` kautta.  Kun tuo tapahtuu, sille annetaan sen ja jokaisen yliluokan kontekstit, ja kun se lisää depsinsä `_set_dependencies` kutsulla, `dependencies_contexts` ei olekaan enää `None`, ja graph rakennetaan. Tällä myös vältymme graphin luomiselta n-kertaa.

2017-10-23 07:51 UTC, closed without merging